name: Build Python App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          mkdir -p dist
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            pyinstaller --onefile my_app.py --distpath dist/
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            pyinstaller --onefile my_app.py --distpath dist/
            sudo apt-get update && sudo apt-get install -y ruby ruby-dev build-essential
            gem install --no-document fpm
            fpm -s dir -t deb -n my_app -v 1.0 dist/my_app=/usr/local/bin/
          else
            pyinstaller --onefile my_app.py --distpath dist/
            pip install py2app
            python setup.py py2app -O2

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my_app_${{ runner.os }}
          path: dist/
